project:
  type: website
  output-dir: docs

website:
  title: "Morgane Henry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: full

editor: visual

