project:
  type: website
  output-dir: docs

website:
  title: "Morgane Henry"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: CV.qmd
        text: CV 
  page-footer:
    background: primary
    right:
      - icon: envelope-fill
        text: morgane.henry2@mail.mcgill.ca
    left: "Copyright 2026, Morgane Henry" 

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    page-layout: full

editor: visual

