---
title: "Publications"
toc: false
--- 

## Published articles

::: {.publication}
**Henry, M.**, James, P. M. A, Kneeshaw, D. & Leung, B. (2026) Connecting the dots: elucidating the relationship between spruce budworm population dynamics and defoliation. *Canadian Journal of Forest Research* <https://doi.org/10.1139/cjfr-2025-0197>
:::

::: {.publication}
Ghali, K., Ramella, E., **Henry, M.**, Schwander, T., & van der Kooi, C. J. (2025). Ecological specialization, clonal diversity, and local adaptation explain the co-existence of sexual and asexual grass thrips. *Journal of evolutionary biology*, 38(7), 1016-1022. <https://doi.org/10.1093/jeb/voaf076>
:::

::: {.publication}
Hudgins, E. J., Leung, B., MacQuarrie, C. J., McCullough, D. G., Francis, A., Lovett, G. M., Guo, Q., Potter, K. M., Cullingham, C. I., Koch, F. H., Bergman, J. N., Binley, A. D., Robichaud, C., **Henry, M.**, Chen, Yuyan, C. & Bennett, J. R. (2024). Five organizing themes for invasive forest insect and disease management in Canada and the United States. *Forest Ecology and Management*, 566, 122046. <https://doi.org/10.1016/j.foreco.2024.122046>
:::

::: {.publication}
**Henry, M.**, Leung, B., Cuthbert, R. N., Bodey, T. W., Ahmed, D. A., Angulo, E., ... & Haubrock, P. J. (2023). Unveiling the hidden economic toll of biological invasions in the European Union. *Environmental Sciences Europe*, 35(1), 1-16. <https://doi.org/10.1186/s12302-023-00750-3>
:::


## Preprints

::: {.publication}
de Oliveira Caetano, G.H., Angulo, E., Carneiro, L., Cuthbert, R.N., Evans, T., **Henry, M.**, Hudgins, E., Soto, I., Touza, J., Turbelin, A.J., Jarić, I. & Courchamp, F. (2025) Global extrapolation drastically increases estimated economic costs of biological invasions [preprint] <https://doi.org/10.21203/rs.3.rs-5825547/v1>
:::